### ISSUE TITLE
MUC

### ISSUE THREAD

**Issue by bobykus31** [jelmer/prometheus-xmpp-alerts#7]
Can I post alerts to chat room with  prometheus-xmpp-alerts?

**Comment by jelmer** [comment]
No, posting alerts to mucs is not supported yet.

**Comment by genofire** [comment]
Would be nice.

**Comment by ichthyx** [comment]
Hello,
added muc support here https://github.com/ichthyx/prometheus-xmpp-alerts
I'll do a pr when I have time

**Comment by jelmer** [comment]
This has landed based on @ichthyx changes; closing.
