### ISSUE TITLE
immediate crash from aiowsgi

### ISSUE THREAD

**Issue by azrdev** [jelmer/prometheus-xmpp-alerts#8]
~~~
/var/lib/prometheus-xmpp-alerts/.local/bin/prometheus-xmpp-alerts:108: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
detected unhandled Python exception in '/var/lib/prometheus-xmpp-alerts/.local/bin/prometheus-xmpp-alerts'
Traceback (most recent call last):
  File "/var/lib/prometheus-xmpp-alerts/.local/bin/prometheus-xmpp-alerts", line 152, in <module>
    port=config['listen_port'], host=config['listen_address'])
  File "/var/lib/prometheus-xmpp-alerts/.local/lib/python3.6/site-packages/aiowsgi/__init__.py", line 110, in create_server
    server_name=server.server_name,
AttributeError: 'MultiSocketServer' object has no attribute 'server_name'
~~~

this is current HEAD, i.e. daba8d9 

config file is valid, but apparently irrelevant
~~~yaml
jid: dummy@example.com
listen_address: localhost
listen_port: 9199
to_jid: other@example.com
~~~

**Comment by azrdev** [comment]
Seems like `localhost` resolves to two addresses (`127.0.0.1` and `::1`) [making](https://github.com/Pylons/waitress/blob/ecea02ff58896ceba149dba17260b05735cbe5b4/waitress/server.py#L112..L121) `waitress.create_server` return a `waitress.MultiSocketServer` instead of `waitress.TcpWSGIServer`, which doesn't have the `server_name` attribute.

**Comment by jelmer** [comment]
On Thu, May 09, 2019 at 02:03:35PM -0700, azrdev wrote:
> Seems like `localhost` resolves to two addresses (`127.0.0.1` and `::1`) [making](https://github.com/Pylons/waitress/blob/ecea02ff58896ceba149dba17260b05735cbe5b4/waitress/server.py#L112..L121) `waitress.create_server` return a `waitress.MultiSocketServer` instead of `waitress.TcpWSGIServer`, which doesn't have the `server_name` attribute.
Can you try current master? I was considering migrating to aiohttp so I've just gone ahead and made that change.

**Comment by azrdev** [comment]
@jelmer thank you!  works fine with binding to localhost and `curl http://localhost:9199/test`. I'm trying to use it from grafana, though, which seems to offer only POST instead of GET, and thus fails with `Webhook response status 405 Method Not Allowed`

**Comment by jelmer** [comment]
On Sun, May 12, 2019 at 05:12:07AM -0700, azrdev wrote:
> @jelmer thank you!  works fine with binding to localhost and `curl http://localhost:9199/test`. I'm trying to use it from grafana, though, which seems to offer only POST instead of GET, and thus fails with `Webhook response status 405 Method Not Allowed`
Oops, my bad. I actually ran into that as well, but forgot to push the fix earlier. Can you try now?

**Comment by azrdev** [comment]
@jelmer I did, works fine. I'd offer `/test` and `/alert` on the same method(s) to avoid confusion, see https://github.com/jelmer/prometheus-xmpp-alerts/commit/6ca363865f3ed6d80233f3d3f3c593783bffa5e3
However using this for grafana seems not straight-forward, since their json body differs significantly from what prometheus-alertmanager sends:

~~~json
{
  "evalMatches": [
    {
      "value": 100,
      "metric": "High value",
      "tags": null
    },
    {
      "value": 200,
      "metric": "Higher Value",
      "tags": null
    }
  ],
  "imageUrl": "https://grafana.com/assets/img/blog/mixed_styles.png",
  "message": "Someone is testing the alert notification within grafana.",
  "ruleId": 0,
  "ruleName": "Test notification",
  "ruleUrl": "XXX",
  "state": "alerting",
  "title": "[Alerting] Test notification"
}
~~~
