### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by jangrewe** [jelmer/prometheus-xmpp-alerts#9]
I was trying to hook my Alertmanager up to my XMPP server (Prosody), but it looks like your code doesn't like it? :-(

I guess this happens because i don't allow SSLv3 anymore - any chance you could add support for TLSv1.1+?

https://xmpp.net/result.php?id=1456415

```
======== Running on http://127.0.0.1:9199 ========
(Press CTRL+C to quit)
ERROR    CERT: Invalid certificate trust chain.
ERROR    Fatal write error on socket transport
protocol: <__main__.XmppApp object at 0x7f757a832eb8>
transport: <_SelectorSocketTransport fd=6 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/slixmpp/xmlstream/xmlstream.py", line 500, in ssl_coro
    transp, prot = yield from ssl_connect_routine
  File "/usr/lib/python3.5/asyncio/base_events.py", line 801, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 827, in _create_connection_transport
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 865, in _on_handshake
    self._sock.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 761, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor
INFO     connection_lost: (OSError(9, 'Bad file descriptor'),)
INFO     Connection lost, exiting.
```

**Comment by jelmer** [comment]
I think the main error here is:
ERROR    CERT: Invalid certificate trust chain.

prometheus-xmpp-alerts uses slixmpp for XMPP and it just uses the regular Python SSL module for TLS; the latter supports TLSv1.1+

**Comment by jangrewe** [comment]
I'm using Let's Encrypt, and from the link above you can see that my cert is valid and has a valid chain of trust. That report also says it supports TLS1.0/1.1/1.2, which is why i'm so surprised about that SSLv3 error! :-)

I tried forcing TLSv1.2 by editing your code with an adjusted example from the SLIXMPP docs, but that didn't seem to work and still resulted in the error. Maybe it's actually a problem with my Python version/libraries, which is what Debian stretch currently ships.

**Comment by jelmer** [comment]
FWIW I'm running Debian sid and my server also has SSLv2/SSLv3 disabled, but prometheus-xmpp-alerts is working fine with it. That may indeed suggest that it's an issue with the older python3/slixmpp in stretch.

**Comment by jangrewe** [comment]
Alright, i guess i'll just pack it into a Docker image then, to create a controlled environment. Probably also a PR to get that upstreamed. ;-)

**Comment by MarkusEckerl** [comment]
I have got the same problem on Debian Buster. Two machines. Both upgraded (apt dist-upgrade) from Stretch. It seems to me that SLIXMPP is the same version on Sid and Buster. So why doesnt it work as expected on Buster?

**Comment by jelmer** [comment]
Please provide the exact traceback you're seeing.

**Comment by MarkusEckerl** [comment]
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]: transport: <_SelectorSocketTransport closing fd=10 read=idle write=<idle, bufs
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]: Traceback (most recent call last):
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]:   File "/usr/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]:     ssldata, appdata = self._sslpipe.feed_ssldata(data)
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]:   File "/usr/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]:     self._sslobj.do_handshake()
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]:   File "/usr/lib/python3.7/ssl.py", line 763, in do_handshake
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]:     self._sslobj.do_handshake()
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]: ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failu
Aug 20 13:27:24 mon-1 prometheus-xmpp-alerts[18742]: ERROR    CERT: Invalid certificate trust chain.

**Comment by jelmer** [comment]
This looks like a general slixmpp issue on Debian; see e.g. https://github.com/marconfus/ha-nefit-ng/issues/6#issuecomment-493750683

**Comment by MarkusEckerl** [comment]
Well, I had thought this before. But what to do now? File a bug at the Debian maintainers?
